name: Build and Deploy

on:
  push:
    branches:
      - mod

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # or your required version

      - name: Debug Show repo files
        run: ls -la

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8  # or your pnpm version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Deploy to publish branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: publish
          publish_dir: ./dist
          force_orphan: true
